# Generated by Django 4.2 on 2023-04-04 16:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('rue', models.CharField(max_length=100)),
                ('no_entree', models.CharField(max_length=10)),
                ('npa', models.IntegerField()),
                ('localite', models.CharField(max_length=50)),
                ('coord', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
