# Generated by Django 4.2 on 2023-04-05 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deplacements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id_mode', models.AutoField(primary_key=True, serialize=False)),
                ('nom_mode', models.CharField(max_length=100)),
                ('alias_mode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id_motif', models.AutoField(primary_key=True, serialize=False)),
                ('nom_motif', models.CharField(max_length=100)),
                ('alias_motif', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Raison',
            fields=[
                ('id_raison', models.AutoField(primary_key=True, serialize=False)),
                ('nom_raison', models.CharField(max_length=100)),
                ('alias_raison', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id_site', models.AutoField(primary_key=True, serialize=False)),
                ('nom_site', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='lieu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='localite',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='no_entree',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='npa',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='rue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id_societe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_societe', models.CharField(max_length=100)),
                ('sites', models.ManyToManyField(to='deplacements.site')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deplacements.lieu'),
        ),
        migrations.CreateModel(
            name='Domicile',
            fields=[
                ('id_domicile', models.AutoField(primary_key=True, serialize=False)),
                ('nom_domicile', models.CharField(max_length=100)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deplacements.lieu')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deplacement',
            fields=[
                ('id_deplacement', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure_depart', models.TimeField()),
                ('heure_arrivee', models.TimeField()),
                ('mode', models.CharField(max_length=100)),
                ('motif', models.CharField(max_length=100)),
                ('raison', models.CharField(max_length=100)),
                ('lieu_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deplacements_arrivee', to='deplacements.lieu')),
                ('lieu_depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deplacements_depart', to='deplacements.lieu')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
