# Generated by Django 4.2 on 2023-04-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deplacements', '0002_mode_motif_raison_site_alter_lieu_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='sites',
            field=models.ManyToManyField(blank=True, to='deplacements.site'),
        ),
    ]
