# Generated by Django 4.2 on 2023-04-06 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deplacements', '0003_alter_societe_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='utilisateurs',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='npa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Domicile',
        ),
    ]
