# Generated by Django 4.2 on 2023-04-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deplacements', '0004_lieu_utilisateurs_alter_lieu_npa_delete_domicile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deplacement',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deplacements.mode'),
        ),
        migrations.AlterField(
            model_name='deplacement',
            name='motif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deplacements.motif'),
        ),
        migrations.AlterField(
            model_name='deplacement',
            name='raison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deplacements.raison'),
        ),
    ]
