# Generated by Django 4.2 on 2023-04-08 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deplacements', '0005_alter_deplacement_mode_alter_deplacement_motif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id_fonction', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fonction', models.CharField(max_length=100)),
                ('alias_fonction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Taux',
            fields=[
                ('id_taux', models.AutoField(primary_key=True, serialize=False)),
                ('taux', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='lieu',
            options={'verbose_name_plural': 'Lieux'},
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id_profil', models.AutoField(primary_key=True, serialize=False)),
                ('pmr', models.BooleanField()),
                ('bike_to_work', models.BooleanField()),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deplacements.fonction')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deplacements.site')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deplacements.societe')),
                ('taux', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deplacements.taux')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
