# Generated by Django 4.2 on 2023-04-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deplacements', '0006_fonction_taux_alter_lieu_options_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taux',
            options={'verbose_name_plural': 'Taux'},
        ),
        migrations.AlterField(
            model_name='taux',
            name='taux',
            field=models.CharField(max_length=3),
        ),
    ]
